version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:1234@host.docker.internal:5432/task_management
      - API_KEY=softblend123
    volumes:
      - .:/app
